[deps]
AllocCheck = "9b6a8646-10ed-4001-bbdc-1d2f46dfbb1a"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
StrictMode = "0e98b4f4-d0e6-42ac-af0a-707c24852f32"

[sources]
StrictMode = {path = ".."}

[preferences.StrictMode]
checks_enabled = true
analysis = "fast"
